# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c8b2b5c467b77659fcd99916924749678ad9854ed1855c6426d7c19374485c4369e29b4a45f4bdb26d8e94ff45648ee53e49e4f120a9fd77c1478ef29d22834f

test:
  secret_key_base: 446ab7f7783af8acf13bbfa7d4713e35e221e4a67ac74697a89345dabd9bdfc5751d6aebb2d6170418c344af3eb26602e738b9fded77c757217a25a78583f70f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
